[book]
authors = ["Garth Braithwaite"]
language = "en"
multilingual = false
src = "src"
title = "metal-candle Guide"

[build]
build-dir = "book"
create-missing = true

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/GarthDB/metal-candle"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/GarthDB/metal-candle/edit/main/docs/{path}"

[output.html.fold]
enable = true
level = 1

[output.html.search]
enable = true

[output.html.print]
enable = false
